############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1


[[main]]
name = "Treatment Expertise"
url = "/treatment-expertise"
weight = 2

[[main]]
weight = 4
name = "From Dr. Mitra's Desk"
url = "/desk"

# footer menu
[[footer]]
name = "From Dr. Mitra's Desk"
url = "/desk"
weight = 4

[[footer]]
name = "Privacy Policy"
url = "privacy-policy"
weight = 2

[[footer]]
name = "Contact Us"
url = "contact"
weight = 3